### ISSUE TITLE
Card heights are weird all around. 

### ISSUE THREAD

**Issue by vshivam** [adaszyn/bookie-app#25]
The note cards have different heights depending on the content. Same with book cards. 

In the book view, expanding the details of a book makes the thumbnail container's height go all crazy. 

@adaszyn You'll need to check this one out man. I tried to solve it without giving fixed heights to the cards but couldn't to do it.

**Comment by adaszyn** [comment]
`In the book view, expanding the details of a book makes the thumbnail container's height go all crazy.` - fixed
