### ISSUE TITLE
Show longer text in book description.

### ISSUE THREAD

**Issue by vshivam** [adaszyn/bookie-app#47]
@adaszyn There is a lot of space in the book view to show a longer text description by default. I had increased the default length of text but (I think) you decreased it back again. Any specific reasons ?
 
![screenshot from 2018-05-04 02-13-38](https://user-images.githubusercontent.com/831071/39608304-d4590684-4f40-11e8-8378-c401012888e3.png)

**Comment by adaszyn** [comment]
I didn't want to implement customized `SearchResult` and `SearchResults` components - they use `description` property from data object. We can use `full_description` field in NoteView instead of `descrption`. I will take care of that.

**Comment by adaszyn** [comment]
@vshivam Alternatively (if we have time) we could use `description` only and manipulate it in components (SearchResults and SearchResult)

**Comment by vshivam** [comment]
Ahh! Got it.

-Shivam
