### ISSUE TITLE
NoteView does not show content. 

### ISSUE THREAD

**Issue by vshivam** [adaszyn/bookie-app#60]
Open Edit Note for some note, press back then press forward in the browser.

The content doesn't show up.

**Comment by vshivam** [comment]
Line number 24 in NotesView causes the problem.

**Comment by vshivam** [comment]
I dont think this one is fixed yet. I still get the same problem. Or am I the only one ?

**Comment by ranjini1992** [comment]
@vshivam godmorgon!! i think this is fixed now but i'm really not sure if that's the best way of doing it. could you please check the changes in RTEContainer componentWillReceiveProps? this class wasn't receiving the props value from notes view earlier. but then again, it reloads with every keypress. so had to add some weird if statement.

**Comment by adaszyn** [comment]
@ranjini1992 I'll take a loot at that.
