### ISSUE TITLE
Shouldn't we just use the existing components from the BookView instead of adding a whole another view for all notes ?

### ISSUE THREAD

**Issue by vshivam** [adaszyn/bookie-app#61]

**Comment by vshivam** [comment]
We can add the other sorting options to the toolbar.

**Comment by ranjini1992** [comment]
1. yup the notes list from book view would look better.
2. do we really need any other sorting options? i guess searching for a text in any note is more useful.

**Comment by adaszyn** [comment]
Agree. However, I think there's no need for switching between List/Tile mode in that view.

**Comment by adaszyn** [comment]
I added toolbar on master.
