### ISSUE TITLE
Should cancel button behave like pressing back on browser ..

### ISSUE THREAD

**Issue by vshivam** [adaszyn/bookie-app#63]
.. rather than as a link. Intuitively, if I press cancel in the edit screen, I'd like to navigate back to the edit screen by pressing forward on the browser.

**Comment by vshivam** [comment]
Reddit has the same behavior. If we press cancel when creating a new post, it takes us back.

**Comment by adaszyn** [comment]
Sounds ok for me.

**Comment by vshivam** [comment]
Done
