### ISSUE TITLE
Show Drop Zone for Draggable Tags. 

### ISSUE THREAD

**Issue by vshivam** [adaszyn/bookie-app#71]
Same as we did for drag to upload image ?

**Comment by adaszyn** [comment]
Yeah, agree. Who can take it?

**Comment by vshivam** [comment]
I'll do it.

**Comment by vshivam** [comment]
This is done but it does seem to throw a warning once for some reason (check console). Possibly a lifecycle issue. If anyone can fix it, it'll be nice. I might spend some time on it later.
